//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYM.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public int id_client { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public string Mail { get; set; }
        public int Phone { get; set; }
        public System.DateTime DataBirth { get; set; }
        public Nullable<int> Lvl { get; set; }
        public Nullable<int> Rank_id { get; set; }
    
        public virtual Rank Rank { get; set; }
    }
}
