//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYM.Components
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GHUMIKA : DbContext
    {
        public GHUMIKA()
            : base("name=GHUMIKA")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Emploeys> Emploeys { get; set; }
        public virtual DbSet<Exescise> Exescise { get; set; }
        public virtual DbSet<Master> Master { get; set; }
        public virtual DbSet<Rolee> Rolee { get; set; }
        public virtual DbSet<Service> Service { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Timesheet> Timesheet { get; set; }
        public virtual DbSet<Visits> Visits { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Rank> Rank { get; set; }
    }
}
