//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYM.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visits
    {
        public int id_visit { get; set; }
        public int numr_card { get; set; }
        public int id_record { get; set; }
    
        public virtual Timesheet Timesheet { get; set; }
    }
}
